Add dependences on nose >= 0.9.1 and modify script to launch tests from bamboo
git-svn-id: https://nosexunit.svn.sourceforge.net/svnroot/nosexunit/trunk@5 549516f5-ea2c-0410-bc29-f7564ae968c0

diff --git a/NoseXUnit/bamboo b/NoseXUnit/bamboo
--- a/NoseXUnit/bamboo
+++ b/NoseXUnit/bamboo
@@ -8,16 +8,21 @@ export PATH
 LD_LIBRARY_PATH=$PYTHONHOME/lib
 export LD_LIBRARY_PATH
 
-# Get all the argument for nosetests except the first one
-shift 1
-
-# Install NoseXUnit and its dependences
-python setup.py install
-if [ $? -ne 0 ]
+# Get the goals for setup.py
+GOALS=$2
+if [ "${GOALS}" != "skip" ]
 then
-    echo "ERROR: failed to install NoseXUnit"
-    exit 1
+    # Launch the goals
+    python setup.py ${GOALS}
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR: python setup.py ${GOALS} failed"
+        exit 1
+    fi
 fi
+
+# Get all the argument for nosetests except the first one
+shift 2
 
 # Call nosetests
 nosetests $*
